<a href="https://colab.research.google.com/github/goldspruce/2048/blob/master/VizCog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.signal import convolve2d

def filter(input_matrix, filter_matrix):
    """
    Apply filter to a visual field input matrix

    """
    # 'valid' is no zero-padding
    feature_map = convolve2d(input_matrix, filter_matrix, mode='valid')

    return feature_map

input_matrix = np.array([[1, 2, 3, 0, 3],
                          [4, 5, 6, 1, 4],
                          [7, 8, 9, 2, 5],
                          [0, 1, 2, 3, 6],
                          [0, 1, 4, 2, 5]
                        ])

filter_matrix = np.array([[1, 0],
                           [0, -1]])

result = filter(input_matrix, filter_matrix)
print(filter_matrix)
print("Apply filter:")
print(result)

[[ 1  0]
 [ 0 -1]]
Apply filter:
[[ 4  4 -2  4]
 [ 4  4 -4  4]
 [-6 -6 -6  4]
 [ 1  3  0  2]]


In [ ]:
def filtered(input_matrix, filter_matrix):

    # validate input dimensions
    input_rows, input_cols = input_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    if kernel_rows > input_rows or kernel_cols > input_cols:
        raise ValueError("Kernel dimensions must be same or smaller than the input dimensions.")

    # output size
    output_rows = input_rows - kernel_rows + 1
    output_cols = input_cols - kernel_cols + 1
    output = np.zeros((output_rows, output_cols))

    for i in range(output_rows):
        for j in range(output_cols):
            # Extract the region of the input_matrix corresponding to the kernel
            region = input_matrix[i:i + kernel_rows, j:j + kernel_cols]
            # Compute the dot product between the kernel and the region
            output[i, j] = np.sum(region * kernel)

    return output

def sliding_dot_product(input_matrix, kernel):

    # validate input dimensions
    input_rows, input_cols = input_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    if kernel_rows > input_rows or kernel_cols > input_cols:
        raise ValueError("Kernel dimensions must be same or smaller than the input dimensions.")

    # output size
    output_rows = input_rows - kernel_rows + 1
    output_cols = input_cols - kernel_cols + 1
    output = np.zeros((output_rows, output_cols))

    for i in range(output_rows):
        for j in range(output_cols):
            # Extract the region of the input_matrix corresponding to the kernel
            region = input_matrix[i:i + kernel_rows, j:j + kernel_cols]
            # Compute the dot product between the kernel and the region
            output[i, j] = np.sum(region * kernel)

    return output

input_matrix = np.array([[1, 2, 3, 0, 3],
                          [4, 5, 6, 1, 4],
                          [7, 8, 9, 2, 5],
                          [0, 1, 2, 3, 6],
                          [0, 1, 4, 2, 5]
                        ])

filter_matrix = np.array([[1, 1],
                   [1, 1]])

kernel = np.array([[-1, 0],
                   [0, 1]])

filtered = sliding_dot_product(input_matrix, filter_matrix)
result = sliding_dot_product(input_matrix, kernel)
print("Filtered before kernel:")
print(filtered)
print("Filter plus kernel:")
print(result)

Filtered before kernel:
[[12. 16. 10.  8.]
 [24. 28. 18. 12.]
 [16. 20. 16. 16.]
 [ 2.  8. 11. 16.]]
Filter plus kernel:
[[ 4.  4. -2.  4.]
 [ 4.  4. -4.  4.]
 [-6. -6. -6.  4.]
 [ 1.  3.  0.  2.]]
